name: TacticalMonsters
author: Rayzs_YT

main: de.rayzs.tacticalmonsters.TacticalMonstersLoader
description: Gives monsters a variety of different attacks.

version: 1.0.0
api-version: 1.13

commands:
  tacticalmonstersreload:
    aliases: [tmreload, tmr]
    description: Reloads all files and settings.
    permission: tacticalmonsters.reload
